# Generated by Django 5.2.13 on 2026-05-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name_course', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationStage',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name_education_stage', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'education_stages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name_exam_types', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final')], max_length=20)),
            ],
            options={
                'db_table': 'exam_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('years_number', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'years',
                'managed': False,
            },
        ),
    ]
