# Generated by Django 5.2.13 on 2026-05-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'exam_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentExamAnswer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'student_exam_answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentExamAttempt',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'student_exam_attempts',
                'managed': False,
            },
        ),
    ]
