# Generated by Django 5.2.13 on 2026-05-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('descriptive', 'Descriptive')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('descriptive_answer_text', models.TextField()),
            ],
            options={
                'db_table': 'question_answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('option_number', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'question_choices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('pdf', 'PDF'), ('document', 'Document')], max_length=20)),
                ('file_url', models.CharField(max_length=2048)),
                ('original_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionSelectedOption',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_selected_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionStatusHistory',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_status_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionWorkflowStatus',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question_workflow_statuses',
                'managed': False,
            },
        ),
    ]
