# Generated by Django 5.2.13 on 2026-06-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'مدیریت پلن\u200cهای اشتراک',
                'db_table': 'subscription_plans',
                'ordering': ['-created_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'اشتراک کاربر',
                'verbose_name_plural': 'مدیریت اشتراک کاربران',
                'db_table': 'user_subscriptions',
                'ordering': ['-start_date', '-id'],
                'managed': False,
            },
        ),
    ]
